// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/bff/bff.proto

package bff

import (
	backend "github.com/keitaj/grpc-federation-demo/proto/backend"
	_ "github.com/mercari/grpc-federation/grpc/federation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserViolationType defines validation errors for all user-related operations
type UserViolationType int32

const (
	// This is never used.
	UserViolationType_USER_VIOLATION_TYPE_UNSPECIFIED UserViolationType = 0
	// User not found
	UserViolationType_USER_VIOLATION_TYPE_USER_NOT_FOUND UserViolationType = 1
	// User account is suspended
	UserViolationType_USER_VIOLATION_TYPE_ACCOUNT_SUSPENDED UserViolationType = 2
)

// Enum value maps for UserViolationType.
var (
	UserViolationType_name = map[int32]string{
		0: "USER_VIOLATION_TYPE_UNSPECIFIED",
		1: "USER_VIOLATION_TYPE_USER_NOT_FOUND",
		2: "USER_VIOLATION_TYPE_ACCOUNT_SUSPENDED",
	}
	UserViolationType_value = map[string]int32{
		"USER_VIOLATION_TYPE_UNSPECIFIED":       0,
		"USER_VIOLATION_TYPE_USER_NOT_FOUND":    1,
		"USER_VIOLATION_TYPE_ACCOUNT_SUSPENDED": 2,
	}
)

func (x UserViolationType) Enum() *UserViolationType {
	p := new(UserViolationType)
	*p = x
	return p
}

func (x UserViolationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserViolationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bff_bff_proto_enumTypes[0].Descriptor()
}

func (UserViolationType) Type() protoreflect.EnumType {
	return &file_proto_bff_bff_proto_enumTypes[0]
}

func (x UserViolationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserViolationType.Descriptor instead.
func (UserViolationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{0}
}

// OrderViolationType defines validation errors for all order-related operations
type OrderViolationType int32

const (
	// This is never used.
	OrderViolationType_ORDER_VIOLATION_TYPE_UNSPECIFIED OrderViolationType = 0
	// Order not found
	OrderViolationType_ORDER_VIOLATION_TYPE_ORDER_NOT_FOUND OrderViolationType = 1
	// Order is cancelled
	OrderViolationType_ORDER_VIOLATION_TYPE_ORDER_CANCELLED OrderViolationType = 2
	// Order has no items
	OrderViolationType_ORDER_VIOLATION_TYPE_NO_ITEMS OrderViolationType = 3
)

// Enum value maps for OrderViolationType.
var (
	OrderViolationType_name = map[int32]string{
		0: "ORDER_VIOLATION_TYPE_UNSPECIFIED",
		1: "ORDER_VIOLATION_TYPE_ORDER_NOT_FOUND",
		2: "ORDER_VIOLATION_TYPE_ORDER_CANCELLED",
		3: "ORDER_VIOLATION_TYPE_NO_ITEMS",
	}
	OrderViolationType_value = map[string]int32{
		"ORDER_VIOLATION_TYPE_UNSPECIFIED":     0,
		"ORDER_VIOLATION_TYPE_ORDER_NOT_FOUND": 1,
		"ORDER_VIOLATION_TYPE_ORDER_CANCELLED": 2,
		"ORDER_VIOLATION_TYPE_NO_ITEMS":        3,
	}
)

func (x OrderViolationType) Enum() *OrderViolationType {
	p := new(OrderViolationType)
	*p = x
	return p
}

func (x OrderViolationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderViolationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bff_bff_proto_enumTypes[1].Descriptor()
}

func (OrderViolationType) Type() protoreflect.EnumType {
	return &file_proto_bff_bff_proto_enumTypes[1]
}

func (x OrderViolationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderViolationType.Descriptor instead.
func (OrderViolationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{1}
}

// ProductViolationType defines validation errors for all product-related operations
type ProductViolationType int32

const (
	// This is never used.
	ProductViolationType_PRODUCT_VIOLATION_TYPE_UNSPECIFIED ProductViolationType = 0
	// Product not found
	ProductViolationType_PRODUCT_VIOLATION_TYPE_PRODUCT_NOT_FOUND ProductViolationType = 1
	// Product is out of stock
	ProductViolationType_PRODUCT_VIOLATION_TYPE_PRODUCT_OUT_OF_STOCK ProductViolationType = 2
)

// Enum value maps for ProductViolationType.
var (
	ProductViolationType_name = map[int32]string{
		0: "PRODUCT_VIOLATION_TYPE_UNSPECIFIED",
		1: "PRODUCT_VIOLATION_TYPE_PRODUCT_NOT_FOUND",
		2: "PRODUCT_VIOLATION_TYPE_PRODUCT_OUT_OF_STOCK",
	}
	ProductViolationType_value = map[string]int32{
		"PRODUCT_VIOLATION_TYPE_UNSPECIFIED":          0,
		"PRODUCT_VIOLATION_TYPE_PRODUCT_NOT_FOUND":    1,
		"PRODUCT_VIOLATION_TYPE_PRODUCT_OUT_OF_STOCK": 2,
	}
)

func (x ProductViolationType) Enum() *ProductViolationType {
	p := new(ProductViolationType)
	*p = x
	return p
}

func (x ProductViolationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductViolationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bff_bff_proto_enumTypes[2].Descriptor()
}

func (ProductViolationType) Type() protoreflect.EnumType {
	return &file_proto_bff_bff_proto_enumTypes[2]
}

func (x ProductViolationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductViolationType.Descriptor instead.
func (ProductViolationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{2}
}

// UserErrorReason defines unavailable error reasons for user service
type UserErrorReason int32

const (
	UserErrorReason_USER_ERROR_REASON_UNSPECIFIED      UserErrorReason = 0
	UserErrorReason_USER_ERROR_REASON_MAINTENANCE      UserErrorReason = 1
	UserErrorReason_USER_ERROR_REASON_UNEXPECTED_ERROR UserErrorReason = 2
)

// Enum value maps for UserErrorReason.
var (
	UserErrorReason_name = map[int32]string{
		0: "USER_ERROR_REASON_UNSPECIFIED",
		1: "USER_ERROR_REASON_MAINTENANCE",
		2: "USER_ERROR_REASON_UNEXPECTED_ERROR",
	}
	UserErrorReason_value = map[string]int32{
		"USER_ERROR_REASON_UNSPECIFIED":      0,
		"USER_ERROR_REASON_MAINTENANCE":      1,
		"USER_ERROR_REASON_UNEXPECTED_ERROR": 2,
	}
)

func (x UserErrorReason) Enum() *UserErrorReason {
	p := new(UserErrorReason)
	*p = x
	return p
}

func (x UserErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bff_bff_proto_enumTypes[3].Descriptor()
}

func (UserErrorReason) Type() protoreflect.EnumType {
	return &file_proto_bff_bff_proto_enumTypes[3]
}

func (x UserErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserErrorReason.Descriptor instead.
func (UserErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{3}
}

// OrderErrorReason defines unavailable error reasons for order service
type OrderErrorReason int32

const (
	OrderErrorReason_ORDER_ERROR_REASON_UNSPECIFIED      OrderErrorReason = 0
	OrderErrorReason_ORDER_ERROR_REASON_MAINTENANCE      OrderErrorReason = 1
	OrderErrorReason_ORDER_ERROR_REASON_UNEXPECTED_ERROR OrderErrorReason = 2
)

// Enum value maps for OrderErrorReason.
var (
	OrderErrorReason_name = map[int32]string{
		0: "ORDER_ERROR_REASON_UNSPECIFIED",
		1: "ORDER_ERROR_REASON_MAINTENANCE",
		2: "ORDER_ERROR_REASON_UNEXPECTED_ERROR",
	}
	OrderErrorReason_value = map[string]int32{
		"ORDER_ERROR_REASON_UNSPECIFIED":      0,
		"ORDER_ERROR_REASON_MAINTENANCE":      1,
		"ORDER_ERROR_REASON_UNEXPECTED_ERROR": 2,
	}
)

func (x OrderErrorReason) Enum() *OrderErrorReason {
	p := new(OrderErrorReason)
	*p = x
	return p
}

func (x OrderErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bff_bff_proto_enumTypes[4].Descriptor()
}

func (OrderErrorReason) Type() protoreflect.EnumType {
	return &file_proto_bff_bff_proto_enumTypes[4]
}

func (x OrderErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderErrorReason.Descriptor instead.
func (OrderErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{4}
}

// ProductErrorReason defines unavailable error reasons for product service
type ProductErrorReason int32

const (
	ProductErrorReason_PRODUCT_ERROR_REASON_UNSPECIFIED      ProductErrorReason = 0
	ProductErrorReason_PRODUCT_ERROR_REASON_MAINTENANCE      ProductErrorReason = 1
	ProductErrorReason_PRODUCT_ERROR_REASON_UNEXPECTED_ERROR ProductErrorReason = 2
)

// Enum value maps for ProductErrorReason.
var (
	ProductErrorReason_name = map[int32]string{
		0: "PRODUCT_ERROR_REASON_UNSPECIFIED",
		1: "PRODUCT_ERROR_REASON_MAINTENANCE",
		2: "PRODUCT_ERROR_REASON_UNEXPECTED_ERROR",
	}
	ProductErrorReason_value = map[string]int32{
		"PRODUCT_ERROR_REASON_UNSPECIFIED":      0,
		"PRODUCT_ERROR_REASON_MAINTENANCE":      1,
		"PRODUCT_ERROR_REASON_UNEXPECTED_ERROR": 2,
	}
)

func (x ProductErrorReason) Enum() *ProductErrorReason {
	p := new(ProductErrorReason)
	*p = x
	return p
}

func (x ProductErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bff_bff_proto_enumTypes[5].Descriptor()
}

func (ProductErrorReason) Type() protoreflect.EnumType {
	return &file_proto_bff_bff_proto_enumTypes[5]
}

func (x ProductErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductErrorReason.Descriptor instead.
func (ProductErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{5}
}

type GetUserWithOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWithOrdersRequest) Reset() {
	*x = GetUserWithOrdersRequest{}
	mi := &file_proto_bff_bff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWithOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWithOrdersRequest) ProtoMessage() {}

func (x *GetUserWithOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_bff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWithOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserWithOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserWithOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserWithOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *backend.User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Orders        []*backend.Order       `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalOrders   int32                  `protobuf:"varint,3,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWithOrdersResponse) Reset() {
	*x = GetUserWithOrdersResponse{}
	mi := &file_proto_bff_bff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWithOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWithOrdersResponse) ProtoMessage() {}

func (x *GetUserWithOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_bff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWithOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetUserWithOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserWithOrdersResponse) GetUser() *backend.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserWithOrdersResponse) GetOrders() []*backend.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetUserWithOrdersResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

type GetOrderDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailsRequest) Reset() {
	*x = GetOrderDetailsRequest{}
	mi := &file_proto_bff_bff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailsRequest) ProtoMessage() {}

func (x *GetOrderDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_bff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderDetailsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderDetailsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Order          *backend.Order         `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	User           *backend.User          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ProductDetails []*ProductDetail       `protobuf:"bytes,3,rep,name=product_details,json=productDetails,proto3" json:"product_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrderDetailsResponse) Reset() {
	*x = GetOrderDetailsResponse{}
	mi := &file_proto_bff_bff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailsResponse) ProtoMessage() {}

func (x *GetOrderDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_bff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderDetailsResponse) GetOrder() *backend.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderDetailsResponse) GetUser() *backend.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetOrderDetailsResponse) GetProductDetails() []*ProductDetail {
	if x != nil {
		return x.ProductDetails
	}
	return nil
}

type ProductDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *backend.Product       `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDetail) Reset() {
	*x = ProductDetail{}
	mi := &file_proto_bff_bff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetail) ProtoMessage() {}

func (x *ProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_bff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetail.ProtoReflect.Descriptor instead.
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{4}
}

func (x *ProductDetail) GetProduct() *backend.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ProductDetail) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductDetail) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

type GetUserDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDashboardRequest) Reset() {
	*x = GetUserDashboardRequest{}
	mi := &file_proto_bff_bff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDashboardRequest) ProtoMessage() {}

func (x *GetUserDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_bff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetUserDashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserDashboardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserDashboardResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	User                *backend.User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RecentOrders        []*backend.Order       `protobuf:"bytes,2,rep,name=recent_orders,json=recentOrders,proto3" json:"recent_orders,omitempty"`
	RecommendedProducts []*backend.Product     `protobuf:"bytes,3,rep,name=recommended_products,json=recommendedProducts,proto3" json:"recommended_products,omitempty"`
	Statistics          *UserStatistics        `protobuf:"bytes,4,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetUserDashboardResponse) Reset() {
	*x = GetUserDashboardResponse{}
	mi := &file_proto_bff_bff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDashboardResponse) ProtoMessage() {}

func (x *GetUserDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_bff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetUserDashboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserDashboardResponse) GetUser() *backend.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserDashboardResponse) GetRecentOrders() []*backend.Order {
	if x != nil {
		return x.RecentOrders
	}
	return nil
}

func (x *GetUserDashboardResponse) GetRecommendedProducts() []*backend.Product {
	if x != nil {
		return x.RecommendedProducts
	}
	return nil
}

func (x *GetUserDashboardResponse) GetStatistics() *UserStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type UserStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders   int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	TotalSpent    float64                `protobuf:"fixed64,2,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatistics) Reset() {
	*x = UserStatistics{}
	mi := &file_proto_bff_bff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatistics) ProtoMessage() {}

func (x *UserStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_bff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatistics.ProtoReflect.Descriptor instead.
func (*UserStatistics) Descriptor() ([]byte, []int) {
	return file_proto_bff_bff_proto_rawDescGZIP(), []int{7}
}

func (x *UserStatistics) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *UserStatistics) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

var File_proto_bff_bff_proto protoreflect.FileDescriptor

const file_proto_bff_bff_proto_rawDesc = "" +
	"\n" +
	"\x13proto/bff/bff.proto\x12\x03bff\x1a grpc/federation/federation.proto\x1a\x18proto/backend/user.proto\x1a\x1bproto/backend/product.proto\x1a\x19proto/backend/order.proto\"3\n" +
	"\x18GetUserWithOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf2\r\n" +
	"\x19GetUserWithOrdersResponse\x122\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserB\x12\x9aJ\x0f\x12\ruser_res.userR\x04user\x12<\n" +
	"\x06orders\x18\x02 \x03(\v2\f.order.OrderB\x16\x9aJ\x13\x12\x11orders_res.ordersR\x06orders\x128\n" +
	"\ftotal_orders\x18\x03 \x01(\x05B\x15\x9aJ\x12\x12\x10orders_res.totalR\vtotalOrders:\xa8\f\x9aJ\xa4\f\n" +
	"\xe4\x05\n" +
	"\buser_resr\xd7\x05\n" +
	"\x18user.UserService/GetUser\x12\x14\n" +
	"\auser_id\x12\t$.user_id\x1a\x025s\"k\x1a^error.code != google.rpc.Code.FAILED_PRECONDITION && error.code != google.rpc.Code.UNAVAILABLE\x12\t\n" +
	"\x05250ms(\x01*\xde\x02\n" +
	"\x83\x01\n" +
	"\x0eviolation_type\x82\x01p\n" +
	"\x11UserViolationType\x12[user.UserFailureCode.value(error.precondition_failures[?0].violations[?0].type.orValue(''))\x12Cviolation_type != UserViolationType.USER_VIOLATION_TYPE_UNSPECIFIED\x18\t\"\x02''*\x8a\x01BN\n" +
	"L\n" +
	"&UserViolationType.name(violation_type)\x12\x13'GetUserWithOrders'\x1a\rerror.messagej8\n" +
	"\x05ja-JP\x12/UserViolationType.attr(violation_type, 'ja-JP')*\xd2\x01\n" +
	"g\n" +
	"\ferror_reason\x82\x01V\n" +
	"\x0fUserErrorReason\x12Cuser.UserErrorReason.value(error.error_info[?0].reason.orValue(''))\x12)error.code == google.rpc.Code.UNAVAILABLE\x18\x0e\"\x02''*6j4\n" +
	"\x05ja-JP\x12+UserErrorReason.attr(error_reason, 'ja-JP')\n" +
	"\xba\x06\n" +
	"\n" +
	"orders_resr\xab\x06\n" +
	"#order.OrderService/ListOrdersByUser\x12\x14\n" +
	"\auser_id\x12\t$.user_id\x12\v\n" +
	"\x05limit\x12\x0210\x12\v\n" +
	"\x06offset\x12\x010\x1a\x025s\"k\x1a^error.code != google.rpc.Code.FAILED_PRECONDITION && error.code != google.rpc.Code.UNAVAILABLE\x12\t\n" +
	"\x05250ms(\x01*\xfd\x02\n" +
	"\x8c\x01\n" +
	"\x14order_violation_type\x82\x01s\n" +
	"\x12OrderViolationType\x12]order.OrderFailureCode.value(error.precondition_failures[?0].violations[?0].type.orValue(''))\x12Korder_violation_type != OrderViolationType.ORDER_VIOLATION_TYPE_UNSPECIFIED\x18\t\"\x02''*\x98\x01BU\n" +
	"S\n" +
	"-OrderViolationType.name(order_violation_type)\x12\x13'GetUserWithOrders'\x1a\rerror.messagej?\n" +
	"\x05ja-JP\x126OrderViolationType.attr(order_violation_type, 'ja-JP')*\xe2\x01\n" +
	"p\n" +
	"\x12order_error_reason\x82\x01Y\n" +
	"\x10OrderErrorReason\x12Eorder.OrderErrorReason.value(error.error_info[?0].reason.orValue(''))\x12)error.code == google.rpc.Code.UNAVAILABLE\x18\x0e\"\x02''*=j;\n" +
	"\x05ja-JP\x122OrderErrorReason.attr(order_error_reason, 'ja-JP')\"3\n" +
	"\x16GetOrderDetailsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xe3\x0e\n" +
	"\x17GetOrderDetailsResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderB\x0e\x9aJ\v\x12\tthe_orderR\x05order\x122\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".user.UserB\x12\x9aJ\x0f\x12\ruser_res.userR\x04user\x12Q\n" +
	"\x0fproduct_details\x18\x03 \x03(\v2\x12.bff.ProductDetailB\x14\x9aJ\x11\x12\x0fproduct_detailsR\x0eproductDetails:\x8c\r\x9aJ\x88\r\n" +
	"\xf3\x05\n" +
	"\torder_resr\xe5\x05\n" +
	"\x1border.OrderService/GetOrder\x12\x16\n" +
	"\border_id\x12\n" +
	"$.order_id\x1a\x025s\"k\x1a^error.code != google.rpc.Code.FAILED_PRECONDITION && error.code != google.rpc.Code.UNAVAILABLE\x12\t\n" +
	"\x05250ms(\x01*\xe3\x02\n" +
	"\x86\x01\n" +
	"\x0eviolation_type\x82\x01s\n" +
	"\x12OrderViolationType\x12]order.OrderFailureCode.value(error.precondition_failures[?0].violations[?0].type.orValue(''))\x12Eviolation_type != OrderViolationType.ORDER_VIOLATION_TYPE_UNSPECIFIED\x18\t\"\x02''*\x8a\x01BM\n" +
	"K\n" +
	"'OrderViolationType.name(violation_type)\x12\x11'GetOrderDetails'\x1a\rerror.messagej9\n" +
	"\x05ja-JP\x120OrderViolationType.attr(violation_type, 'ja-JP')*\xd6\x01\n" +
	"j\n" +
	"\ferror_reason\x82\x01Y\n" +
	"\x10OrderErrorReason\x12Eorder.OrderErrorReason.value(error.error_info[?0].reason.orValue(''))\x12)error.code == google.rpc.Code.UNAVAILABLE\x18\x0e\"\x02''*7j5\n" +
	"\x05ja-JP\x12,OrderErrorReason.attr(error_reason, 'ja-JP')\n" +
	"\x1c\n" +
	"\tthe_orderZ\x0forder_res.order\n" +
	"\x1e\n" +
	"\vorder_itemsZ\x0fthe_order.items\n" +
	"\x88\x06\n" +
	"\buser_resr\xfb\x05\n" +
	"\x18user.UserService/GetUser\x12\x1c\n" +
	"\auser_id\x12\x11the_order.user_id\x1a\x025s\"k\x1a^error.code != google.rpc.Code.FAILED_PRECONDITION && error.code != google.rpc.Code.UNAVAILABLE\x12\t\n" +
	"\x05250ms(\x01*\xf0\x02\n" +
	"\x88\x01\n" +
	"\x13user_violation_type\x82\x01p\n" +
	"\x11UserViolationType\x12[user.UserFailureCode.value(error.precondition_failures[?0].violations[?0].type.orValue(''))\x12Huser_violation_type != UserViolationType.USER_VIOLATION_TYPE_UNSPECIFIED\x18\t\"\x02''*\x92\x01BQ\n" +
	"O\n" +
	"+UserViolationType.name(user_violation_type)\x12\x11'GetOrderDetails'\x1a\rerror.messagej=\n" +
	"\x05ja-JP\x124UserViolationType.attr(user_violation_type, 'ja-JP')*\xdc\x01\n" +
	"l\n" +
	"\x11user_error_reason\x82\x01V\n" +
	"\x0fUserErrorReason\x12Cuser.UserErrorReason.value(error.error_info[?0].reason.orValue(''))\x12)error.code == google.rpc.Code.UNAVAILABLE\x18\x0e\"\x02''*;j9\n" +
	"\x05ja-JP\x120UserErrorReason.attr(user_error_reason, 'ja-JP')\n" +
	"G\n" +
	"\x0fproduct_detailsb4\n" +
	"\x13\n" +
	"\x04item\x12\vorder_itemsb\x1d\n" +
	"\rProductDetail\x12\f\n" +
	"\x04item\x12\x04item\"\xa2\b\n" +
	"\rProductDetail\x12D\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductB\x18\x9aJ\x15\x12\x13product_res.productR\aproduct\x120\n" +
	"\bquantity\x18\x02 \x01(\x05B\x14\x9aJ\x11\x12\x0f$.item.quantityR\bquantity\x12G\n" +
	"\bsubtotal\x18\x03 \x01(\x01B+\x9aJ(\x12&double($.item.quantity) * $.item.priceR\bsubtotal:\xcf\x06\x9aJ\xcb\x06\n" +
	"\xc8\x06\n" +
	"\vproduct_resr\xb8\x06\n" +
	"!product.ProductService/GetProduct\x12\x1f\n" +
	"\n" +
	"product_id\x12\x11$.item.product_id\x1a\x025s\"k\x1a^error.code != google.rpc.Code.FAILED_PRECONDITION && error.code != google.rpc.Code.UNAVAILABLE\x12\t\n" +
	"\x05250ms(\x01*\x9f\x03\n" +
	"\x94\x01\n" +
	"\x16product_violation_type\x82\x01y\n" +
	"\x14ProductViolationType\x12aproduct.ProductFailureCode.value(error.precondition_failures[?0].violations[?0].type.orValue(''))\x12Qproduct_violation_type != ProductViolationType.PRODUCT_VIOLATION_TYPE_UNSPECIFIED\x18\t\"\x02''*\xac\x01Be\n" +
	"c\n" +
	"1ProductViolationType.name(product_violation_type)\x12\x1f'GetOrderDetails/ProductDetail'\x1a\rerror.messagejC\n" +
	"\x05ja-JP\x12:ProductViolationType.attr(product_violation_type, 'ja-JP')*\xde\x01\n" +
	"p\n" +
	"\ferror_reason\x82\x01_\n" +
	"\x12ProductErrorReason\x12Iproduct.ProductErrorReason.value(error.error_info[?0].reason.orValue(''))\x12)error.code == google.rpc.Code.UNAVAILABLE\x18\x0e\"\x02''*9j7\n" +
	"\x05ja-JP\x12.ProductErrorReason.attr(error_reason, 'ja-JP')\"2\n" +
	"\x17GetUserDashboardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9d\x16\n" +
	"\x18GetUserDashboardResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserB\r\x9aJ\n" +
	"\x12\bthe_userR\x04user\x12I\n" +
	"\rrecent_orders\x18\x02 \x03(\v2\f.order.OrderB\x16\x9aJ\x13\x12\x11orders_res.ordersR\frecentOrders\x12_\n" +
	"\x14recommended_products\x18\x03 \x03(\v2\x10.product.ProductB\x1a\x9aJ\x17\x12\x15products_res.productsR\x13recommendedProducts\x12?\n" +
	"\n" +
	"statistics\x18\x04 \x01(\v2\x13.bff.UserStatisticsB\n" +
	"\x9aJ\a\x12\x05statsR\n" +
	"statistics:\xe4\x13\x9aJ\xe0\x13\n" +
	"\xe3\x05\n" +
	"\buser_resr\xd6\x05\n" +
	"\x18user.UserService/GetUser\x12\x14\n" +
	"\auser_id\x12\t$.user_id\x1a\x025s\"k\x1a^error.code != google.rpc.Code.FAILED_PRECONDITION && error.code != google.rpc.Code.UNAVAILABLE\x12\t\n" +
	"\x05250ms(\x01*\xdd\x02\n" +
	"\x83\x01\n" +
	"\x0eviolation_type\x82\x01p\n" +
	"\x11UserViolationType\x12[user.UserFailureCode.value(error.precondition_failures[?0].violations[?0].type.orValue(''))\x12Cviolation_type != UserViolationType.USER_VIOLATION_TYPE_UNSPECIFIED\x18\t\"\x02''*\x89\x01BM\n" +
	"K\n" +
	"&UserViolationType.name(violation_type)\x12\x12'GetUserDashboard'\x1a\rerror.messagej8\n" +
	"\x05ja-JP\x12/UserViolationType.attr(violation_type, 'ja-JP')*\xd2\x01\n" +
	"g\n" +
	"\ferror_reason\x82\x01V\n" +
	"\x0fUserErrorReason\x12Cuser.UserErrorReason.value(error.error_info[?0].reason.orValue(''))\x12)error.code == google.rpc.Code.UNAVAILABLE\x18\x0e\"\x02''*6j4\n" +
	"\x05ja-JP\x12+UserErrorReason.attr(error_reason, 'ja-JP')\n" +
	"\x19\n" +
	"\bthe_userZ\ruser_res.user\n" +
	"\xb9\x06\n" +
	"\n" +
	"orders_resr\xaa\x06\n" +
	"#order.OrderService/ListOrdersByUser\x12\x14\n" +
	"\auser_id\x12\t$.user_id\x12\v\n" +
	"\x05limit\x12\x0210\x12\v\n" +
	"\x06offset\x12\x010\x1a\x025s\"k\x1a^error.code != google.rpc.Code.FAILED_PRECONDITION && error.code != google.rpc.Code.UNAVAILABLE\x12\t\n" +
	"\x05250ms(\x01*\xfc\x02\n" +
	"\x8c\x01\n" +
	"\x14order_violation_type\x82\x01s\n" +
	"\x12OrderViolationType\x12]order.OrderFailureCode.value(error.precondition_failures[?0].violations[?0].type.orValue(''))\x12Korder_violation_type != OrderViolationType.ORDER_VIOLATION_TYPE_UNSPECIFIED\x18\t\"\x02''*\x97\x01BT\n" +
	"R\n" +
	"-OrderViolationType.name(order_violation_type)\x12\x12'GetUserDashboard'\x1a\rerror.messagej?\n" +
	"\x05ja-JP\x126OrderViolationType.attr(order_violation_type, 'ja-JP')*\xe2\x01\n" +
	"p\n" +
	"\x12order_error_reason\x82\x01Y\n" +
	"\x10OrderErrorReason\x12Eorder.OrderErrorReason.value(error.error_info[?0].reason.orValue(''))\x12)error.code == google.rpc.Code.UNAVAILABLE\x18\x0e\"\x02''*=j;\n" +
	"\x05ja-JP\x122OrderErrorReason.attr(order_error_reason, 'ja-JP')\n" +
	"\xc6\x06\n" +
	"\fproducts_resr\xb5\x06\n" +
	"#product.ProductService/ListProducts\x12\n" +
	"\n" +
	"\x05limit\x12\x015\x12\v\n" +
	"\x06offset\x12\x010\x1a\x025s\"k\x1a^error.code != google.rpc.Code.FAILED_PRECONDITION && error.code != google.rpc.Code.UNAVAILABLE\x12\t\n" +
	"\x05250ms(\x01*\x92\x03\n" +
	"\x94\x01\n" +
	"\x16product_violation_type\x82\x01y\n" +
	"\x14ProductViolationType\x12aproduct.ProductFailureCode.value(error.precondition_failures[?0].violations[?0].type.orValue(''))\x12Qproduct_violation_type != ProductViolationType.PRODUCT_VIOLATION_TYPE_UNSPECIFIED\x18\t\"\x02''*\x9f\x01BX\n" +
	"V\n" +
	"1ProductViolationType.name(product_violation_type)\x12\x12'GetUserDashboard'\x1a\rerror.messagejC\n" +
	"\x05ja-JP\x12:ProductViolationType.attr(product_violation_type, 'ja-JP')*\xee\x01\n" +
	"x\n" +
	"\x14product_error_reason\x82\x01_\n" +
	"\x12ProductErrorReason\x12Iproduct.ProductErrorReason.value(error.error_info[?0].reason.orValue(''))\x12)error.code == google.rpc.Code.UNAVAILABLE\x18\x0e\"\x02''*Aj?\n" +
	"\x05ja-JP\x126ProductErrorReason.attr(product_error_reason, 'ja-JP')\n" +
	"X\n" +
	"\x05statsjO\n" +
	"\x0eUserStatistics\x12 \n" +
	"\ftotal_orders\x12\x10orders_res.total\x12\x1b\n" +
	"\x06orders\x12\x11orders_res.orders\"x\n" +
	"\x0eUserStatistics\x126\n" +
	"\ftotal_orders\x18\x01 \x01(\x05B\x13\x9aJ\x10\x12\x0e$.total_ordersR\vtotalOrders\x12)\n" +
	"\vtotal_spent\x18\x02 \x01(\x01B\b\x9aJ\x05\x12\x030.0R\n" +
	"totalSpent:\x03\x9aJ\x00*\x9c\x04\n" +
	"\x11UserViolationType\x12\xa6\x01\n" +
	"\x1fUSER_VIOLATION_TYPE_UNSPECIFIED\x10\x00\x1a\x80\x01\x9aJ}\b\x01\x12\x1dUSER_FAILURE_CODE_UNSPECIFIED\x1aZ\n" +
	"\x05ja-JP\x12Qエラーが発生しました。時間をおいて再度お試しください。\x12\xa9\x01\n" +
	"\"USER_VIOLATION_TYPE_USER_NOT_FOUND\x10\x01\x1a\x80\x01\x9aJ}\x12 USER_FAILURE_CODE_USER_NOT_FOUND\x1aY\n" +
	"\x05ja-JP\x12Pユーザーが見つかりません。ユーザーIDをご確認ください。\x12\x96\x01\n" +
	"%USER_VIOLATION_TYPE_ACCOUNT_SUSPENDED\x10\x02\x1ak\x9aJh\x12(USER_FAILURE_CODE_USER_ACCOUNT_SUSPENDED\x1a<\n" +
	"\x05ja-JP\x123このアカウントは停止されています。\x1a\x19\x9aJ\x16\n" +
	"\x14user.UserFailureCode*\xc4\x05\n" +
	"\x12OrderViolationType\x12\xa8\x01\n" +
	" ORDER_VIOLATION_TYPE_UNSPECIFIED\x10\x00\x1a\x81\x01\x9aJ~\b\x01\x12\x1eORDER_FAILURE_CODE_UNSPECIFIED\x1aZ\n" +
	"\x05ja-JP\x12Qエラーが発生しました。時間をおいて再度お試しください。\x12\xa0\x01\n" +
	"$ORDER_VIOLATION_TYPE_ORDER_NOT_FOUND\x10\x01\x1av\x9aJs\x12\"ORDER_FAILURE_CODE_ORDER_NOT_FOUND\x1aM\n" +
	"\x05ja-JP\x12D注文が見つかりません。注文IDをご確認ください。\x12\xb5\x01\n" +
	"$ORDER_VIOLATION_TYPE_ORDER_CANCELLED\x10\x02\x1a\x8a\x01\x9aJ\x86\x01\x12\"ORDER_FAILURE_CODE_ORDER_CANCELLED\x1a`\n" +
	"\x05ja-JP\x12Wこの注文はキャンセルされているため、詳細を表示できません。\x12\x8a\x01\n" +
	"\x1dORDER_VIOLATION_TYPE_NO_ITEMS\x10\x03\x1ag\x9aJd\x12!ORDER_FAILURE_CODE_ORDER_NO_ITEMS\x1a?\n" +
	"\x05ja-JP\x126この注文には商品が含まれていません。\x1a\x1b\x9aJ\x18\n" +
	"\x16order.OrderFailureCode*\xa3\x04\n" +
	"\x14ProductViolationType\x12\xad\x01\n" +
	"\"PRODUCT_VIOLATION_TYPE_UNSPECIFIED\x10\x00\x1a\x84\x01\x9aJ\x80\x01\b\x01\x12 PRODUCT_FAILURE_CODE_UNSPECIFIED\x1aZ\n" +
	"\x05ja-JP\x12Qエラーが発生しました。時間をおいて再度お試しください。\x12\xa8\x01\n" +
	"(PRODUCT_VIOLATION_TYPE_PRODUCT_NOT_FOUND\x10\x01\x1az\x9aJw\x12&PRODUCT_FAILURE_CODE_PRODUCT_NOT_FOUND\x1aM\n" +
	"\x05ja-JP\x12D商品が見つかりません。商品IDをご確認ください。\x12\x8e\x01\n" +
	"+PRODUCT_VIOLATION_TYPE_PRODUCT_OUT_OF_STOCK\x10\x02\x1a]\x9aJZ\x12)PRODUCT_FAILURE_CODE_PRODUCT_OUT_OF_STOCK\x1a-\n" +
	"\x05ja-JP\x12$この商品は在庫切れです。\x1a\x1f\x9aJ\x1c\n" +
	"\x1aproduct.ProductFailureCode*\xad\x05\n" +
	"\x0fUserErrorReason\x12\xa4\x01\n" +
	"\x1dUSER_ERROR_REASON_UNSPECIFIED\x10\x00\x1a\x80\x01\x9aJ}\b\x01\x12\x1dUSER_ERROR_REASON_UNSPECIFIED\x1aZ\n" +
	"\x05ja-JP\x12Qエラーが発生しました。時間をおいて再度お試しください。\x12\xf9\x01\n" +
	"\x1dUSER_ERROR_REASON_MAINTENANCE\x10\x01\x1a\xd5\x01\x9aJ\xd1\x01\x12\x1dUSER_ERROR_REASON_MAINTENANCE\x1a\xaf\x01\n" +
	"\x05ja-JP\x12\xa5\x01システムメンテナンス中のため、ユーザーサービスをご利用いただけません。メンテナンス終了後に再度お試しください。\x12\xdb\x01\n" +
	"\"USER_ERROR_REASON_UNEXPECTED_ERROR\x10\x02\x1a\xb2\x01\x9aJ\xae\x01\x12\"USER_ERROR_REASON_UNEXPECTED_ERROR\x1a\x87\x01\n" +
	"\x05ja-JP\x12~ユーザーサービスでシステムエラーが発生しました。しばらくしてから再度お試しください。\x1a\x19\x9aJ\x16\n" +
	"\x14user.UserErrorReason*\xaa\x05\n" +
	"\x10OrderErrorReason\x12\xa6\x01\n" +
	"\x1eORDER_ERROR_REASON_UNSPECIFIED\x10\x00\x1a\x81\x01\x9aJ~\b\x01\x12\x1eORDER_ERROR_REASON_UNSPECIFIED\x1aZ\n" +
	"\x05ja-JP\x12Qエラーが発生しました。時間をおいて再度お試しください。\x12\xf5\x01\n" +
	"\x1eORDER_ERROR_REASON_MAINTENANCE\x10\x01\x1a\xd0\x01\x9aJ\xcc\x01\x12\x1eORDER_ERROR_REASON_MAINTENANCE\x1a\xa9\x01\n" +
	"\x05ja-JP\x12\x9f\x01システムメンテナンス中のため、注文サービスをご利用いただけません。メンテナンス終了後に再度お試しください。\x12\xd7\x01\n" +
	"#ORDER_ERROR_REASON_UNEXPECTED_ERROR\x10\x02\x1a\xad\x01\x9aJ\xa9\x01\x12#ORDER_ERROR_REASON_UNEXPECTED_ERROR\x1a\x81\x01\n" +
	"\x05ja-JP\x12x注文サービスでシステムエラーが発生しました。しばらくしてから再度お試しください。\x1a\x1b\x9aJ\x18\n" +
	"\x16order.OrderErrorReason*\xbd\x05\n" +
	"\x12ProductErrorReason\x12\xab\x01\n" +
	" PRODUCT_ERROR_REASON_UNSPECIFIED\x10\x00\x1a\x84\x01\x9aJ\x80\x01\b\x01\x12 PRODUCT_ERROR_REASON_UNSPECIFIED\x1aZ\n" +
	"\x05ja-JP\x12Qエラーが発生しました。時間をおいて再度お試しください。\x12\xf9\x01\n" +
	" PRODUCT_ERROR_REASON_MAINTENANCE\x10\x01\x1a\xd2\x01\x9aJ\xce\x01\x12 PRODUCT_ERROR_REASON_MAINTENANCE\x1a\xa9\x01\n" +
	"\x05ja-JP\x12\x9f\x01システムメンテナンス中のため、商品サービスをご利用いただけません。メンテナンス終了後に再度お試しください。\x12\xdb\x01\n" +
	"%PRODUCT_ERROR_REASON_UNEXPECTED_ERROR\x10\x02\x1a\xaf\x01\x9aJ\xab\x01\x12%PRODUCT_ERROR_REASON_UNEXPECTED_ERROR\x1a\x81\x01\n" +
	"\x05ja-JP\x12x商品サービスでシステムエラーが発生しました。しばらくしてから再度お試しください。\x1a\x1f\x9aJ\x1c\n" +
	"\x1aproduct.ProductErrorReason2\x84\x02\n" +
	"\n" +
	"BFFService\x12R\n" +
	"\x11GetUserWithOrders\x12\x1d.bff.GetUserWithOrdersRequest\x1a\x1e.bff.GetUserWithOrdersResponse\x12L\n" +
	"\x0fGetOrderDetails\x12\x1b.bff.GetOrderDetailsRequest\x1a\x1c.bff.GetOrderDetailsResponse\x12O\n" +
	"\x10GetUserDashboard\x12\x1c.bff.GetUserDashboardRequest\x1a\x1d.bff.GetUserDashboardResponse\x1a\x03\x9aJ\x00B\x87\x01\x9aJR\x12\x18proto/backend/user.proto\x12\x1bproto/backend/product.proto\x12\x19proto/backend/order.protoZ0github.com/keitaj/grpc-federation-demo/proto/bffb\x06proto3"

var (
	file_proto_bff_bff_proto_rawDescOnce sync.Once
	file_proto_bff_bff_proto_rawDescData []byte
)

func file_proto_bff_bff_proto_rawDescGZIP() []byte {
	file_proto_bff_bff_proto_rawDescOnce.Do(func() {
		file_proto_bff_bff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bff_bff_proto_rawDesc), len(file_proto_bff_bff_proto_rawDesc)))
	})
	return file_proto_bff_bff_proto_rawDescData
}

var file_proto_bff_bff_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_bff_bff_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_bff_bff_proto_goTypes = []any{
	(UserViolationType)(0),            // 0: bff.UserViolationType
	(OrderViolationType)(0),           // 1: bff.OrderViolationType
	(ProductViolationType)(0),         // 2: bff.ProductViolationType
	(UserErrorReason)(0),              // 3: bff.UserErrorReason
	(OrderErrorReason)(0),             // 4: bff.OrderErrorReason
	(ProductErrorReason)(0),           // 5: bff.ProductErrorReason
	(*GetUserWithOrdersRequest)(nil),  // 6: bff.GetUserWithOrdersRequest
	(*GetUserWithOrdersResponse)(nil), // 7: bff.GetUserWithOrdersResponse
	(*GetOrderDetailsRequest)(nil),    // 8: bff.GetOrderDetailsRequest
	(*GetOrderDetailsResponse)(nil),   // 9: bff.GetOrderDetailsResponse
	(*ProductDetail)(nil),             // 10: bff.ProductDetail
	(*GetUserDashboardRequest)(nil),   // 11: bff.GetUserDashboardRequest
	(*GetUserDashboardResponse)(nil),  // 12: bff.GetUserDashboardResponse
	(*UserStatistics)(nil),            // 13: bff.UserStatistics
	(*backend.User)(nil),              // 14: user.User
	(*backend.Order)(nil),             // 15: order.Order
	(*backend.Product)(nil),           // 16: product.Product
}
var file_proto_bff_bff_proto_depIdxs = []int32{
	14, // 0: bff.GetUserWithOrdersResponse.user:type_name -> user.User
	15, // 1: bff.GetUserWithOrdersResponse.orders:type_name -> order.Order
	15, // 2: bff.GetOrderDetailsResponse.order:type_name -> order.Order
	14, // 3: bff.GetOrderDetailsResponse.user:type_name -> user.User
	10, // 4: bff.GetOrderDetailsResponse.product_details:type_name -> bff.ProductDetail
	16, // 5: bff.ProductDetail.product:type_name -> product.Product
	14, // 6: bff.GetUserDashboardResponse.user:type_name -> user.User
	15, // 7: bff.GetUserDashboardResponse.recent_orders:type_name -> order.Order
	16, // 8: bff.GetUserDashboardResponse.recommended_products:type_name -> product.Product
	13, // 9: bff.GetUserDashboardResponse.statistics:type_name -> bff.UserStatistics
	6,  // 10: bff.BFFService.GetUserWithOrders:input_type -> bff.GetUserWithOrdersRequest
	8,  // 11: bff.BFFService.GetOrderDetails:input_type -> bff.GetOrderDetailsRequest
	11, // 12: bff.BFFService.GetUserDashboard:input_type -> bff.GetUserDashboardRequest
	7,  // 13: bff.BFFService.GetUserWithOrders:output_type -> bff.GetUserWithOrdersResponse
	9,  // 14: bff.BFFService.GetOrderDetails:output_type -> bff.GetOrderDetailsResponse
	12, // 15: bff.BFFService.GetUserDashboard:output_type -> bff.GetUserDashboardResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_bff_bff_proto_init() }
func file_proto_bff_bff_proto_init() {
	if File_proto_bff_bff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bff_bff_proto_rawDesc), len(file_proto_bff_bff_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bff_bff_proto_goTypes,
		DependencyIndexes: file_proto_bff_bff_proto_depIdxs,
		EnumInfos:         file_proto_bff_bff_proto_enumTypes,
		MessageInfos:      file_proto_bff_bff_proto_msgTypes,
	}.Build()
	File_proto_bff_bff_proto = out.File
	file_proto_bff_bff_proto_goTypes = nil
	file_proto_bff_bff_proto_depIdxs = nil
}
