FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy go modules
COPY go.mod go.sum ./

RUN go mod download

# Copy source code
COPY proto/ proto/
COPY backend/ backend/

ARG SERVICE_NAME
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./backend/${SERVICE_NAME}

FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /app/server .

CMD ["./server"]
