version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SERVICE_NAME: user
    ports:
      - "50051:50051"
    networks:
      - grpc-network

  product-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SERVICE_NAME: product
    ports:
      - "50052:50052"
    networks:
      - grpc-network

  order-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SERVICE_NAME: order
    ports:
      - "50053:50053"
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge
