// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/backend/order.proto

package backend

import (
	_ "google.golang.org/genproto/googleapis/rpc/errdetails"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderFailureCode defines error codes for order service
type OrderFailureCode int32

const (
	OrderFailureCode_ORDER_FAILURE_CODE_UNSPECIFIED     OrderFailureCode = 0
	OrderFailureCode_ORDER_FAILURE_CODE_ORDER_NOT_FOUND OrderFailureCode = 10000 // Order does not exist
	OrderFailureCode_ORDER_FAILURE_CODE_ORDER_CANCELLED OrderFailureCode = 10001 // Order has been cancelled
	OrderFailureCode_ORDER_FAILURE_CODE_ORDER_NO_ITEMS  OrderFailureCode = 10002 // Order has no items
)

// Enum value maps for OrderFailureCode.
var (
	OrderFailureCode_name = map[int32]string{
		0:     "ORDER_FAILURE_CODE_UNSPECIFIED",
		10000: "ORDER_FAILURE_CODE_ORDER_NOT_FOUND",
		10001: "ORDER_FAILURE_CODE_ORDER_CANCELLED",
		10002: "ORDER_FAILURE_CODE_ORDER_NO_ITEMS",
	}
	OrderFailureCode_value = map[string]int32{
		"ORDER_FAILURE_CODE_UNSPECIFIED":     0,
		"ORDER_FAILURE_CODE_ORDER_NOT_FOUND": 10000,
		"ORDER_FAILURE_CODE_ORDER_CANCELLED": 10001,
		"ORDER_FAILURE_CODE_ORDER_NO_ITEMS":  10002,
	}
)

func (x OrderFailureCode) Enum() *OrderFailureCode {
	p := new(OrderFailureCode)
	*p = x
	return p
}

func (x OrderFailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderFailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backend_order_proto_enumTypes[0].Descriptor()
}

func (OrderFailureCode) Type() protoreflect.EnumType {
	return &file_proto_backend_order_proto_enumTypes[0]
}

func (x OrderFailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderFailureCode.Descriptor instead.
func (OrderFailureCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{0}
}

// OrderErrorReason defines reasons for unavailable errors
type OrderErrorReason int32

const (
	OrderErrorReason_ORDER_ERROR_REASON_UNSPECIFIED      OrderErrorReason = 0
	OrderErrorReason_ORDER_ERROR_REASON_MAINTENANCE      OrderErrorReason = 1 // System maintenance
	OrderErrorReason_ORDER_ERROR_REASON_UNEXPECTED_ERROR OrderErrorReason = 2 // Unexpected system error
)

// Enum value maps for OrderErrorReason.
var (
	OrderErrorReason_name = map[int32]string{
		0: "ORDER_ERROR_REASON_UNSPECIFIED",
		1: "ORDER_ERROR_REASON_MAINTENANCE",
		2: "ORDER_ERROR_REASON_UNEXPECTED_ERROR",
	}
	OrderErrorReason_value = map[string]int32{
		"ORDER_ERROR_REASON_UNSPECIFIED":      0,
		"ORDER_ERROR_REASON_MAINTENANCE":      1,
		"ORDER_ERROR_REASON_UNEXPECTED_ERROR": 2,
	}
)

func (x OrderErrorReason) Enum() *OrderErrorReason {
	p := new(OrderErrorReason)
	*p = x
	return p
}

func (x OrderErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backend_order_proto_enumTypes[1].Descriptor()
}

func (OrderErrorReason) Type() protoreflect.EnumType {
	return &file_proto_backend_order_proto_enumTypes[1]
}

func (x OrderErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderErrorReason.Descriptor instead.
func (OrderErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PROCESSING  OrderStatus = 2
	OrderStatus_ORDER_STATUS_SHIPPED     OrderStatus = 3
	OrderStatus_ORDER_STATUS_DELIVERED   OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PROCESSING",
		3: "ORDER_STATUS_SHIPPED",
		4: "ORDER_STATUS_DELIVERED",
		5: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PROCESSING":  2,
		"ORDER_STATUS_SHIPPED":     3,
		"ORDER_STATUS_DELIVERED":   4,
		"ORDER_STATUS_CANCELLED":   5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backend_order_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_backend_order_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{2}
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_backend_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_backend_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersByUserRequest) Reset() {
	*x = ListOrdersByUserRequest{}
	mi := &file_proto_backend_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersByUserRequest) ProtoMessage() {}

func (x *ListOrdersByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersByUserRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{2}
}

func (x *ListOrdersByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListOrdersByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersByUserRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListOrdersByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersByUserResponse) Reset() {
	*x = ListOrdersByUserResponse{}
	mi := &file_proto_backend_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersByUserResponse) ProtoMessage() {}

func (x *ListOrdersByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersByUserResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrdersByUserResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersByUserResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_backend_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_backend_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        OrderStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_backend_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{6}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_backend_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_backend_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_proto_backend_order_proto protoreflect.FileDescriptor

const file_proto_backend_order_proto_rawDesc = "" +
	"\n" +
	"\x19proto/backend/order.proto\x12\x05order\x1a\x1egoogle/rpc/error_details.proto\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"6\n" +
	"\x10GetOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"`\n" +
	"\x17ListOrdersByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"V\n" +
	"\x18ListOrdersByUserResponse\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"U\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x05items\x18\x02 \x03(\v2\x10.order.OrderItemR\x05items\"9\n" +
	"\x13CreateOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"\xe5\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.order.OrderItemR\x05items\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\\\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price*\xb0\x01\n" +
	"\x10OrderFailureCode\x12\"\n" +
	"\x1eORDER_FAILURE_CODE_UNSPECIFIED\x10\x00\x12'\n" +
	"\"ORDER_FAILURE_CODE_ORDER_NOT_FOUND\x10\x90N\x12'\n" +
	"\"ORDER_FAILURE_CODE_ORDER_CANCELLED\x10\x91N\x12&\n" +
	"!ORDER_FAILURE_CODE_ORDER_NO_ITEMS\x10\x92N*\x83\x01\n" +
	"\x10OrderErrorReason\x12\"\n" +
	"\x1eORDER_ERROR_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eORDER_ERROR_REASON_MAINTENANCE\x10\x01\x12'\n" +
	"#ORDER_ERROR_REASON_UNEXPECTED_ERROR\x10\x02*\xb4\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17ORDER_STATUS_PROCESSING\x10\x02\x12\x18\n" +
	"\x14ORDER_STATUS_SHIPPED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x052\xe6\x01\n" +
	"\fOrderService\x12;\n" +
	"\bGetOrder\x12\x16.order.GetOrderRequest\x1a\x17.order.GetOrderResponse\x12S\n" +
	"\x10ListOrdersByUser\x12\x1e.order.ListOrdersByUserRequest\x1a\x1f.order.ListOrdersByUserResponse\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponseB6Z4github.com/keitaj/grpc-federation-demo/proto/backendb\x06proto3"

var (
	file_proto_backend_order_proto_rawDescOnce sync.Once
	file_proto_backend_order_proto_rawDescData []byte
)

func file_proto_backend_order_proto_rawDescGZIP() []byte {
	file_proto_backend_order_proto_rawDescOnce.Do(func() {
		file_proto_backend_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backend_order_proto_rawDesc), len(file_proto_backend_order_proto_rawDesc)))
	})
	return file_proto_backend_order_proto_rawDescData
}

var file_proto_backend_order_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_backend_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_backend_order_proto_goTypes = []any{
	(OrderFailureCode)(0),            // 0: order.OrderFailureCode
	(OrderErrorReason)(0),            // 1: order.OrderErrorReason
	(OrderStatus)(0),                 // 2: order.OrderStatus
	(*GetOrderRequest)(nil),          // 3: order.GetOrderRequest
	(*GetOrderResponse)(nil),         // 4: order.GetOrderResponse
	(*ListOrdersByUserRequest)(nil),  // 5: order.ListOrdersByUserRequest
	(*ListOrdersByUserResponse)(nil), // 6: order.ListOrdersByUserResponse
	(*CreateOrderRequest)(nil),       // 7: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),      // 8: order.CreateOrderResponse
	(*Order)(nil),                    // 9: order.Order
	(*OrderItem)(nil),                // 10: order.OrderItem
}
var file_proto_backend_order_proto_depIdxs = []int32{
	9,  // 0: order.GetOrderResponse.order:type_name -> order.Order
	9,  // 1: order.ListOrdersByUserResponse.orders:type_name -> order.Order
	10, // 2: order.CreateOrderRequest.items:type_name -> order.OrderItem
	9,  // 3: order.CreateOrderResponse.order:type_name -> order.Order
	10, // 4: order.Order.items:type_name -> order.OrderItem
	2,  // 5: order.Order.status:type_name -> order.OrderStatus
	3,  // 6: order.OrderService.GetOrder:input_type -> order.GetOrderRequest
	5,  // 7: order.OrderService.ListOrdersByUser:input_type -> order.ListOrdersByUserRequest
	7,  // 8: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	4,  // 9: order.OrderService.GetOrder:output_type -> order.GetOrderResponse
	6,  // 10: order.OrderService.ListOrdersByUser:output_type -> order.ListOrdersByUserResponse
	8,  // 11: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_backend_order_proto_init() }
func file_proto_backend_order_proto_init() {
	if File_proto_backend_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backend_order_proto_rawDesc), len(file_proto_backend_order_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backend_order_proto_goTypes,
		DependencyIndexes: file_proto_backend_order_proto_depIdxs,
		EnumInfos:         file_proto_backend_order_proto_enumTypes,
		MessageInfos:      file_proto_backend_order_proto_msgTypes,
	}.Build()
	File_proto_backend_order_proto = out.File
	file_proto_backend_order_proto_goTypes = nil
	file_proto_backend_order_proto_depIdxs = nil
}
