// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/backend/product.proto

package backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProductFailureCode defines error codes for product service
type ProductFailureCode int32

const (
	ProductFailureCode_PRODUCT_FAILURE_CODE_UNSPECIFIED          ProductFailureCode = 0
	ProductFailureCode_PRODUCT_FAILURE_CODE_PRODUCT_NOT_FOUND    ProductFailureCode = 10000 // Product does not exist
	ProductFailureCode_PRODUCT_FAILURE_CODE_PRODUCT_OUT_OF_STOCK ProductFailureCode = 10001 // Product is out of stock
)

// Enum value maps for ProductFailureCode.
var (
	ProductFailureCode_name = map[int32]string{
		0:     "PRODUCT_FAILURE_CODE_UNSPECIFIED",
		10000: "PRODUCT_FAILURE_CODE_PRODUCT_NOT_FOUND",
		10001: "PRODUCT_FAILURE_CODE_PRODUCT_OUT_OF_STOCK",
	}
	ProductFailureCode_value = map[string]int32{
		"PRODUCT_FAILURE_CODE_UNSPECIFIED":          0,
		"PRODUCT_FAILURE_CODE_PRODUCT_NOT_FOUND":    10000,
		"PRODUCT_FAILURE_CODE_PRODUCT_OUT_OF_STOCK": 10001,
	}
)

func (x ProductFailureCode) Enum() *ProductFailureCode {
	p := new(ProductFailureCode)
	*p = x
	return p
}

func (x ProductFailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductFailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backend_product_proto_enumTypes[0].Descriptor()
}

func (ProductFailureCode) Type() protoreflect.EnumType {
	return &file_proto_backend_product_proto_enumTypes[0]
}

func (x ProductFailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductFailureCode.Descriptor instead.
func (ProductFailureCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{0}
}

// ProductErrorReason defines reasons for unavailable errors
type ProductErrorReason int32

const (
	ProductErrorReason_PRODUCT_ERROR_REASON_UNSPECIFIED      ProductErrorReason = 0
	ProductErrorReason_PRODUCT_ERROR_REASON_MAINTENANCE      ProductErrorReason = 1 // System maintenance
	ProductErrorReason_PRODUCT_ERROR_REASON_UNEXPECTED_ERROR ProductErrorReason = 2 // Unexpected system error
)

// Enum value maps for ProductErrorReason.
var (
	ProductErrorReason_name = map[int32]string{
		0: "PRODUCT_ERROR_REASON_UNSPECIFIED",
		1: "PRODUCT_ERROR_REASON_MAINTENANCE",
		2: "PRODUCT_ERROR_REASON_UNEXPECTED_ERROR",
	}
	ProductErrorReason_value = map[string]int32{
		"PRODUCT_ERROR_REASON_UNSPECIFIED":      0,
		"PRODUCT_ERROR_REASON_MAINTENANCE":      1,
		"PRODUCT_ERROR_REASON_UNEXPECTED_ERROR": 2,
	}
)

func (x ProductErrorReason) Enum() *ProductErrorReason {
	p := new(ProductErrorReason)
	*p = x
	return p
}

func (x ProductErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backend_product_proto_enumTypes[1].Descriptor()
}

func (ProductErrorReason) Type() protoreflect.EnumType {
	return &file_proto_backend_product_proto_enumTypes[1]
}

func (x ProductErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductErrorReason.Descriptor instead.
func (ProductErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{1}
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_backend_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_proto_backend_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_backend_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_backend_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetProductsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDsRequest) Reset() {
	*x = GetProductsByIDsRequest{}
	mi := &file_proto_backend_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDsRequest) ProtoMessage() {}

func (x *GetProductsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductsByIDsRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type GetProductsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDsResponse) Reset() {
	*x = GetProductsByIDsResponse{}
	mi := &file_proto_backend_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDsResponse) ProtoMessage() {}

func (x *GetProductsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductsByIDsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_backend_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_backend_product_proto_rawDescGZIP(), []int{6}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_backend_product_proto protoreflect.FileDescriptor

const file_proto_backend_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/backend/product.proto\x12\aproduct\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"@\n" +
	"\x12GetProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"_\n" +
	"\x13ListProductsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Z\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\":\n" +
	"\x17GetProductsByIDsRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\"H\n" +
	"\x18GetProductsByIDsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\"\xb6\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt*\x97\x01\n" +
	"\x12ProductFailureCode\x12$\n" +
	" PRODUCT_FAILURE_CODE_UNSPECIFIED\x10\x00\x12+\n" +
	"&PRODUCT_FAILURE_CODE_PRODUCT_NOT_FOUND\x10\x90N\x12.\n" +
	")PRODUCT_FAILURE_CODE_PRODUCT_OUT_OF_STOCK\x10\x91N*\x8b\x01\n" +
	"\x12ProductErrorReason\x12$\n" +
	" PRODUCT_ERROR_REASON_UNSPECIFIED\x10\x00\x12$\n" +
	" PRODUCT_ERROR_REASON_MAINTENANCE\x10\x01\x12)\n" +
	"%PRODUCT_ERROR_REASON_UNEXPECTED_ERROR\x10\x022\xfd\x01\n" +
	"\x0eProductService\x12E\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x1b.product.GetProductResponse\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12W\n" +
	"\x10GetProductsByIDs\x12 .product.GetProductsByIDsRequest\x1a!.product.GetProductsByIDsResponseB6Z4github.com/keitaj/grpc-federation-demo/proto/backendb\x06proto3"

var (
	file_proto_backend_product_proto_rawDescOnce sync.Once
	file_proto_backend_product_proto_rawDescData []byte
)

func file_proto_backend_product_proto_rawDescGZIP() []byte {
	file_proto_backend_product_proto_rawDescOnce.Do(func() {
		file_proto_backend_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backend_product_proto_rawDesc), len(file_proto_backend_product_proto_rawDesc)))
	})
	return file_proto_backend_product_proto_rawDescData
}

var file_proto_backend_product_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_backend_product_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_backend_product_proto_goTypes = []any{
	(ProductFailureCode)(0),          // 0: product.ProductFailureCode
	(ProductErrorReason)(0),          // 1: product.ProductErrorReason
	(*GetProductRequest)(nil),        // 2: product.GetProductRequest
	(*GetProductResponse)(nil),       // 3: product.GetProductResponse
	(*ListProductsRequest)(nil),      // 4: product.ListProductsRequest
	(*ListProductsResponse)(nil),     // 5: product.ListProductsResponse
	(*GetProductsByIDsRequest)(nil),  // 6: product.GetProductsByIDsRequest
	(*GetProductsByIDsResponse)(nil), // 7: product.GetProductsByIDsResponse
	(*Product)(nil),                  // 8: product.Product
}
var file_proto_backend_product_proto_depIdxs = []int32{
	8, // 0: product.GetProductResponse.product:type_name -> product.Product
	8, // 1: product.ListProductsResponse.products:type_name -> product.Product
	8, // 2: product.GetProductsByIDsResponse.products:type_name -> product.Product
	2, // 3: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	4, // 4: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	6, // 5: product.ProductService.GetProductsByIDs:input_type -> product.GetProductsByIDsRequest
	3, // 6: product.ProductService.GetProduct:output_type -> product.GetProductResponse
	5, // 7: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	7, // 8: product.ProductService.GetProductsByIDs:output_type -> product.GetProductsByIDsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_backend_product_proto_init() }
func file_proto_backend_product_proto_init() {
	if File_proto_backend_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backend_product_proto_rawDesc), len(file_proto_backend_product_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backend_product_proto_goTypes,
		DependencyIndexes: file_proto_backend_product_proto_depIdxs,
		EnumInfos:         file_proto_backend_product_proto_enumTypes,
		MessageInfos:      file_proto_backend_product_proto_msgTypes,
	}.Build()
	File_proto_backend_product_proto = out.File
	file_proto_backend_product_proto_goTypes = nil
	file_proto_backend_product_proto_depIdxs = nil
}
