// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/backend/user.proto

package backend

import (
	_ "google.golang.org/genproto/googleapis/rpc/errdetails"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserFailureCode defines error codes for user service
type UserFailureCode int32

const (
	UserFailureCode_USER_FAILURE_CODE_UNSPECIFIED            UserFailureCode = 0
	UserFailureCode_USER_FAILURE_CODE_USER_NOT_FOUND         UserFailureCode = 10000 // User does not exist
	UserFailureCode_USER_FAILURE_CODE_USER_ACCOUNT_SUSPENDED UserFailureCode = 10001 // User account is suspended
)

// Enum value maps for UserFailureCode.
var (
	UserFailureCode_name = map[int32]string{
		0:     "USER_FAILURE_CODE_UNSPECIFIED",
		10000: "USER_FAILURE_CODE_USER_NOT_FOUND",
		10001: "USER_FAILURE_CODE_USER_ACCOUNT_SUSPENDED",
	}
	UserFailureCode_value = map[string]int32{
		"USER_FAILURE_CODE_UNSPECIFIED":            0,
		"USER_FAILURE_CODE_USER_NOT_FOUND":         10000,
		"USER_FAILURE_CODE_USER_ACCOUNT_SUSPENDED": 10001,
	}
)

func (x UserFailureCode) Enum() *UserFailureCode {
	p := new(UserFailureCode)
	*p = x
	return p
}

func (x UserFailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserFailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backend_user_proto_enumTypes[0].Descriptor()
}

func (UserFailureCode) Type() protoreflect.EnumType {
	return &file_proto_backend_user_proto_enumTypes[0]
}

func (x UserFailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserFailureCode.Descriptor instead.
func (UserFailureCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_backend_user_proto_rawDescGZIP(), []int{0}
}

// UserErrorReason defines reasons for unavailable errors
type UserErrorReason int32

const (
	UserErrorReason_USER_ERROR_REASON_UNSPECIFIED      UserErrorReason = 0
	UserErrorReason_USER_ERROR_REASON_MAINTENANCE      UserErrorReason = 1 // System maintenance
	UserErrorReason_USER_ERROR_REASON_UNEXPECTED_ERROR UserErrorReason = 2 // Unexpected system error
)

// Enum value maps for UserErrorReason.
var (
	UserErrorReason_name = map[int32]string{
		0: "USER_ERROR_REASON_UNSPECIFIED",
		1: "USER_ERROR_REASON_MAINTENANCE",
		2: "USER_ERROR_REASON_UNEXPECTED_ERROR",
	}
	UserErrorReason_value = map[string]int32{
		"USER_ERROR_REASON_UNSPECIFIED":      0,
		"USER_ERROR_REASON_MAINTENANCE":      1,
		"USER_ERROR_REASON_UNEXPECTED_ERROR": 2,
	}
)

func (x UserErrorReason) Enum() *UserErrorReason {
	p := new(UserErrorReason)
	*p = x
	return p
}

func (x UserErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_backend_user_proto_enumTypes[1].Descriptor()
}

func (UserErrorReason) Type() protoreflect.EnumType {
	return &file_proto_backend_user_proto_enumTypes[1]
}

func (x UserErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserErrorReason.Descriptor instead.
func (UserErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_backend_user_proto_rawDescGZIP(), []int{1}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_backend_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_backend_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_backend_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_backend_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_backend_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_backend_user_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_backend_user_proto protoreflect.FileDescriptor

const file_proto_backend_user_proto_rawDesc = "" +
	"\n" +
	"\x18proto/backend/user.proto\x12\x04user\x1a\x1egoogle/rpc/error_details.proto\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x0fGetUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"@\n" +
	"\x10ListUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"K\n" +
	"\x11ListUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"q\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt*\x8a\x01\n" +
	"\x0fUserFailureCode\x12!\n" +
	"\x1dUSER_FAILURE_CODE_UNSPECIFIED\x10\x00\x12%\n" +
	" USER_FAILURE_CODE_USER_NOT_FOUND\x10\x90N\x12-\n" +
	"(USER_FAILURE_CODE_USER_ACCOUNT_SUSPENDED\x10\x91N*\x7f\n" +
	"\x0fUserErrorReason\x12!\n" +
	"\x1dUSER_ERROR_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dUSER_ERROR_REASON_MAINTENANCE\x10\x01\x12&\n" +
	"\"USER_ERROR_REASON_UNEXPECTED_ERROR\x10\x022\x83\x01\n" +
	"\vUserService\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12<\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponseB6Z4github.com/keitaj/grpc-federation-demo/proto/backendb\x06proto3"

var (
	file_proto_backend_user_proto_rawDescOnce sync.Once
	file_proto_backend_user_proto_rawDescData []byte
)

func file_proto_backend_user_proto_rawDescGZIP() []byte {
	file_proto_backend_user_proto_rawDescOnce.Do(func() {
		file_proto_backend_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backend_user_proto_rawDesc), len(file_proto_backend_user_proto_rawDesc)))
	})
	return file_proto_backend_user_proto_rawDescData
}

var file_proto_backend_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_backend_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_backend_user_proto_goTypes = []any{
	(UserFailureCode)(0),      // 0: user.UserFailureCode
	(UserErrorReason)(0),      // 1: user.UserErrorReason
	(*GetUserRequest)(nil),    // 2: user.GetUserRequest
	(*GetUserResponse)(nil),   // 3: user.GetUserResponse
	(*ListUsersRequest)(nil),  // 4: user.ListUsersRequest
	(*ListUsersResponse)(nil), // 5: user.ListUsersResponse
	(*User)(nil),              // 6: user.User
}
var file_proto_backend_user_proto_depIdxs = []int32{
	6, // 0: user.GetUserResponse.user:type_name -> user.User
	6, // 1: user.ListUsersResponse.users:type_name -> user.User
	2, // 2: user.UserService.GetUser:input_type -> user.GetUserRequest
	4, // 3: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	3, // 4: user.UserService.GetUser:output_type -> user.GetUserResponse
	5, // 5: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_backend_user_proto_init() }
func file_proto_backend_user_proto_init() {
	if File_proto_backend_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backend_user_proto_rawDesc), len(file_proto_backend_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backend_user_proto_goTypes,
		DependencyIndexes: file_proto_backend_user_proto_depIdxs,
		EnumInfos:         file_proto_backend_user_proto_enumTypes,
		MessageInfos:      file_proto_backend_user_proto_msgTypes,
	}.Build()
	File_proto_backend_user_proto = out.File
	file_proto_backend_user_proto_goTypes = nil
	file_proto_backend_user_proto_depIdxs = nil
}
